Deneb Support
bloxapp/key-vault pull request #100
Opened 2024-01-28 16:43 UTC by olegshmuelov

2024-02-20 15:50 UTC, alonmuroch requested changes

2024-02-20 15:50 UTC, alonmuroch commented on backend/path_sign_proposal_slashing_test.go
> +	// tested against a real block and sig from the goerli testnet (slot 7415521)
where is this taken from?

2024-02-20 15:50 UTC, alonmuroch commented on e2e/tests/proposal_reference_signing.go
> +		Phase0:  blk,
we don't test different versions here?

2024-02-20 15:50 UTC, alonmuroch commented
@olegshmuelov from your end we've covered tests for all different scenarios ?

2024-02-21 09:41 UTC, olegshmuelov commented on go.mod
> +	github.com/bloxapp/eth2-key-manager v1.4.0
the [PR](https://github.com/bloxapp/eth2-key-manager/pull/104) is already merged

2024-02-21 09:51 UTC, olegshmuelov commented on backend/path_sign_proposal_slashing_test.go
> +	// tested against a real block and sig from the goerli testnet (slot 7415521)
The data was taken from the Goerli testnet, specifically from a block signed by a validator whose keys we possess. The slot in question is 7415521. You can reference the corresponding block information through this link: [https://prater.beaconcha.in/block/10389257](https://prater.beaconcha.in/block/10389257).

2024-02-21 12:02 UTC, olegshmuelov commented
> @olegshmuelov from your end we've covered tests for all different scenarios ?

Yes, all scenarios tested, including successful attestations, sync committee participation, and crucially, block proposal duties on Sepolia testnet pre/post-fork with this code version.

2024-02-21 15:52 UTC, olegshmuelov commented on e2e/tests/proposal_reference_signing.go
> +		Phase0:  blk,
Please see https://github.com/bloxapp/key-vault/pull/100/commits/2eb5a6adb6c6146e817c292224345a0f84dd5834

2024-02-25 11:03 UTC, alonmuroch commented on go.mod
> +	github.com/bloxapp/eth2-key-manager v1.4.0
added a few questions there

2024-02-25 11:04 UTC, alonmuroch commented on backend/path_sign_proposal_slashing_test.go
> +	// tested against a real block and sig from the goerli testnet (slot 7415521)
please add as comment

2024-02-29 10:47 UTC, MatheusFranco99 approved these changes
LGTM

2024-02-29 17:22 UTC, moshe-blox approved these changes
LGTM

well done 💪

2024-03-01 12:47 UTC, alonmuroch approved these changes

2024-03-03 15:11 UTC, merged